#!/bin/bash - 
#===============================================================================
#
#          FILE: v
# 
#         USAGE: ./v
# 
#   DESCRIPTION: 
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Marek Płonka (marekpl), marek.plonka@nask.pl
#  ORGANIZATION: NASK
#       CREATED: 12/07/2017 12:38:30 PM
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

new_vm=$1
new_vm_tmp="$new_vm""_tmp"
DOMAIN=`/bin/hostname -d` # Use domain of the host system
DIST_URL="http://ftp.de.debian.org/debian/dists/stretch/main/installer-amd64/"
homes="../home"
conf="../conf"

# prepare files
rm -rf $homes/.vim || true
cp -Rp $HOME/.vim $homes

shopt -s dotglob
pushd $homes
    tar czf ../debian/homes.tgz *
    rm -rf .vim
popd
pushd $conf
    tar czf ../debian/conf.tgz *
popd
shopt -u dotglob

virt-install \
    --connect qemu:///system \
    --name=$new_vm_tmp \
    --memory=2048 \
    --vcpus=2 \
    --disk size=10,cache=writeback \
    --initrd-inject=preseed.cfg \
    --initrd-inject=postinst.sh \
    --initrd-inject=firstboot.sh \
    --initrd-inject=conf.tgz \
    --initrd-inject=homes.tgz \
    --initrd-inject=packages_i.txt \
    --initrd-inject=packages_u.txt \
    --initrd-inject=users.txt \
    --location ${DIST_URL} \
    --os-type linux \
    --os-variant=debian9 \
    --virt-type=kvm \
    --network network=default \
    --graphic none \
    --noreboot \
    --extra-args="auto=true hostname="${new_vm}" domain="${DOMAIN}" console=tty0 console=ttyS0,115200n8 serial"

rm -fv conf.tgz homes.tgz
echo "wait a moment ..." 
sleep 15
virt-clone --connect qemu:///system --original $new_vm_tmp --name $new_vm --file /var/lib/libvirt/images/$new_vm.qcow2

virsh --connect qemu:///system undefine $new_vm_tmp
virsh --connect qemu:///system vol-delete $new_vm_tmp.qcow2 --pool default
virsh --connect qemu:///system start "$new_vm" --console

