    - name: sysvinit - (1) install packages
      apt: name={{ item }} state=installed
      with_items:
        - sysvinit-core
        - sysvinit-utils
      become: yes

    - name: sysvinit - (2) default inittab
      copy:
        src: /usr/share/sysvinit/inittab
        dest: /etc/inittab
        remote_src: yes
        backup: yes
        owner: root
        group: root
        mode: 644
      become: yes
 
    - name: sysvinit - (3) turn on getty on serial console
      shell: sed -i.orig -e 's/^#T0:23:respawn:\/sbin\/getty -L ttyS0 9600 vt100/T0:123:respawn:\/sbin\/getty -L ttyS0 115200 xterm/' /etc/inittab
      become: yes


    - name: reboot the server
      shell: sleep 5 && shutdown -r now
      async: 1
      poll: 0
      become: yes
    - name: Wait for server come back
      wait_for: >
           host={{ inventory_hostname }}
           port=22
           delay=15
           timeout=600
      delegate_to: localhost
    - name: uptime
      shell: uptime
      register: stdout
    - debug: msg="{{ stdout.stdout }} rebooted" verbosity=0


    - name: replace systemd with sysvinit - (4) purge systemd
      apt: name=systemd state=absent autoremove=yes purge=yes
      become: yes

    - name: replace systemd with sysvinit - (5) pinning
      template:
        src: templates/etc/apt/preferences.d/systemd
        dest: /etc/apt/preferences.d/systemd
        owner: root
        group: root
        mode: 0644
      become: yes

